server:
  port: 81
    
spring:
  application:
    name: cloud-dept-consumer-feign
    
eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka
      
      
feign:
  hystrix:
    enabled: true