server:
  port: 9527
  
spring:
  application:
    name: cloud-zuul-gateway
    
eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka
  instance:
    instance-id: 127.0.0.1:9527
    prefer-ip-address: true
    
zuul:
  prefix: /brandon # 统一服务前缀
  ignored-services: cloud-dept
#  ignored-services: * # 忽略所有微服务
  routes:
    mydept.serviceId: cloud-dept
    mydept.path: /mydept/**